"use strict";
const fs = require("node:fs");
const path = require("node:path");
require("./validate-data.js");
if (process.exitCode) process.exit(process.exitCode);
const directory = path.resolve(__dirname, "../data");
const data = JSON.parse(fs.readFileSync(path.join(directory, "ai-history.json"), "utf8"));
fs.writeFileSync(path.join(directory, "ai-history.js"),
  "// Generated by scripts/build-data.js. Edit ai-history.json instead.\n" +
  "window.GinaChronikData = " + JSON.stringify(data, null, 2) + ";\n");
console.log("Browser-Daten aktualisiert.");
